default: &default
  adapter: sqlite3
  pool: 20
  timeout: 5000

development:
  <<: *default
  adapter: postgresql
  database: ask-bot
  host: localhost
  username: root
  password: pass
  pool: 50

production:
  adapter: postgresql
  encoding: unicode
  pool: 30
  url: <%= ENV["DATABASE_URL"] %>