default:
  adapter: postgresql
  pool: 20
  timeout: 5000
development:
  adapter: postgresql
  database: ask-bot
  host: localhost
  password: pass
  pool: 50
  timeout: 5000
  username: root
production:
  adapter: postgresql
  encoding: unicode
  pool: 30
  url: "<%= ENV[\"DATABASE_URL\"] %>"
